<div class="row-fluid">
    <div class="span8">

        <?php
            $params = array(
                'connection_string' => $this->connection_string,
                'action'            => 'history'
            );
        ?>
        <form action="<?php echo $this->url('query', $params) ?>" id="search_form" method="get">
             <div class="input-group">
                <span class="input-group-btn">
                    <button name="search_submit" id="search_button" class="btn btn-default" type="submit">Search</button>
                </span>
                <input type="text" name="search" id="search" class="form-control" value="<?php echo $form->get('search')->getValue() ?>">
            </div>
        </form>
    </div>
</div>
<hr>

<?php
    $params = ($this->connection_string) ? array('connection_string' => $this->connection_string) : array();
?>

<?php foreach ($this->queries as $query): ?>
    
    <?php
        $params['action'] = "connection-list";
        $params['user_id'] = $query->user->user_id;
    ?>
    <a href="<?php echo $this->url('admin', $params) ?>"><?php echo $query->user->user_name ?></a>
    <?php echo " / " ?>

    <?php
        $params['action'] = "index";
        $params['query_id'] = $query->query_id;
    ?>
    <a href="<?php echo $this->url('query', $params) ?>"><?php echo "query #" . $query->query_id ?></a>
    
    <div>
        <small class="text-muted">Created: <?php echo $query->creation_date->format("l F d, Y (m-d-Y)") . " at " . $query->creation_date->format("h:i a") ?></small>
    </div>

    <pre><?php echo $query->query ?></pre>
    <hr>
<?php endforeach ?>