<?php
// module/Application/view/query/index.phtml:

$form = $this->form;
$form->setAttribute('action', $this->url('query', array('action' => 'index')));
$form->prepare();
?>

<form class="form-horizontal" id="query_form" method="post">
    <fieldset>
        <legend>Execute Query</legend>
        <div class="control-group">
            <div class="controls">
                <textarea name="sql" id="sql"><?php echo $form->get('sql')->getValue() ?></textarea>
            </div>
        </div>
        <!--
        <div class="control-group">
            <label for="multiple_queries" class="control-label">Multiple Queries?</label>
            <div class="controls">
                <?php
                    $value = 1;
                    //$value = $this->form->getElement('multiple_queries')->getValue(); 
                ?>
                <input type="radio" name="multiple_queries" id="multiple_queries-1" value="1" <?php echo ($value == 1) ? 'checked="checked"' : ""?>> Yes
                <input type="radio" name="multiple_queries" id="multiple_queries-0" value="0" <?php echo ($value == 0) ? 'checked="checked"' : ""?>> No
            </div>
        </div>
        <div class="control-group">
            <label for="run_in_transaction" class="control-label">Run in transaction?</label>
            <div class="controls">
                <?php
                    $value = 1;
                    // $value = $this->form->getElement('run_in_transaction')->getValue();
                ?>
                <input type="radio" name="run_in_transaction" id="run_in_transaction-1" value="1" <?php echo ($value == 1) ? 'checked="checked"' : ""?>> Yes
                <input type="radio" name="run_in_transaction" id="run_in_transaction-0" value="0" <?php echo ($value == 0) ? 'checked="checked"' : ""?>> No
            </div>
        </div>
        <div class="control-group">
            <label for="query_name" class="control-label">Query Name</label>
            <div class="controls">
                <?php //echo $this->form->getElement('query_name') ?>
                <input type="text" name="query_name">
                <input name="run_submit" type="submit" value="Save" class="btn btn-primary"> <span style="color: #999"></span>
                <span class="help-block">
                    Name your query to be saved for later
                </span>
            </div>
        </div>
        -->
        <br>
        <div class="form-actions">
            <input name="run_submit" type="submit" value="Run" class="btn btn-primary">
            <span style="color: #999">or F5 or SHIFT + ENTER</span>
        </div>
    </fieldset>
</form>



<?php $query_num = 0; ?>
<?php foreach ($results as $result): ?>

<?php $query_num++ ?>
<?php $count = count($result); ?>

<section id="statement_<?php echo $query_num ?>">
    <div class="page-header">
        <h3>
            <strong><?php echo $count; ?></strong> record(s) in *unknown*<strong><?php //echo round($this->logger->queries[$query_num]['executionMS'], 3) ?></strong> seconds <small><?php //echo $this->ellipsize($this->logger->queries[$query_num]['sql'], 100, 0.5) ?></small>
        </h3>
    </div>
    <div class="row">
        <?php if ($count > 0): ?>
        <div style="overflow-x: auto;">
            <table class="table table-condensed table-striped">
                <thead>
                <!--<tr>
                    <?php //foreach (SQLBoss_QueryRunner::getStatementFields($statement) as $field): ?>
                        <th><?php //echo $field['name']; ?></th>
                    <?php //endforeach ?>
                </tr>-->
                </thead>
                <tbody>
                <?php foreach ($result as $row): ?>
                <tr>
                    <?php foreach ($row as $value): ?>
                        <td><?php echo ($value === NULL ? "<em>NULL</em>" : $value) ?></td>
                    <?php endforeach ?>
                </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
        <?php endif ?>
    </div>
</section>
<?php endforeach ?>



<?php foreach ($errors as $error): ?>
    <br>
    <pre class="prettyprint linenums"><?php echo $error ?></pre>
<?php endforeach ?>

<!-- make this better -->
<script type="text/javascript" charset="utf-8" src="<?php echo $this->basePath('js/codemirror-compressed.js') ?>"></script>
<script type="text/javascript" charset="utf-8" src="<?php echo $this->basePath('js/codemirror-config.js') ?>"></script>