<?php

namespace DoctrineORMModule\Proxy\__CG__\Dboss\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Dboss\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }

    /**
     * {@inheritDoc}
     * @param string $name
     */
    public function __get($name)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', array($name));

        return parent::__get($name);
    }

    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'user_id', 'role_id', 'user_name', 'first_name', 'last_name', 'password', 'creation_date', 'modification_date', 'deletion_date', 'role', 'queries', 'connections', 'fields', 'security', 'input_filter');
        }

        return array('__isInitialized__', 'user_id', 'role_id', 'user_name', 'first_name', 'last_name', 'password', 'creation_date', 'modification_date', 'deletion_date', 'role', 'queries', 'connections', 'fields', 'security', 'input_filter');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFields()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFields', array());

        return parent::getFields();
    }

    /**
     * {@inheritDoc}
     */
    public function setInputFilter(\Zend\InputFilter\InputFilterInterface $inputFilter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInputFilter', array($inputFilter));

        return parent::setInputFilter($inputFilter);
    }

    /**
     * {@inheritDoc}
     */
    public function getInputFilter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInputFilter', array());

        return parent::getInputFilter();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function checkPassword($password = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'checkPassword', array($password));

        return parent::checkPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setUserName($user_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserName', array($user_name));

        return parent::setUserName($user_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserName', array());

        return parent::getUserName();
    }

    /**
     * {@inheritDoc}
     */
    public function getRawUserName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRawUserName', array());

        return parent::getRawUserName();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecurity(array $security = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecurity', array($security));

        return parent::setSecurity($security);
    }

    /**
     * {@inheritDoc}
     */
    public function isMyQuery($query_id = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isMyQuery', array($query_id));

        return parent::isMyQuery($query_id);
    }

    /**
     * {@inheritDoc}
     */
    public function isMyConnection($connection_id = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isMyConnection', array($connection_id));

        return parent::isMyConnection($connection_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getMyQuery($query_id = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMyQuery', array($query_id));

        return parent::getMyQuery($query_id);
    }

    /**
     * {@inheritDoc}
     */
    public function isaBoss()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isaBoss', array());

        return parent::isaBoss();
    }

    /**
     * {@inheritDoc}
     */
    public function isLimited()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLimited', array());

        return parent::isLimited();
    }

    /**
     * {@inheritDoc}
     */
    public function canEditUser($user_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'canEditUser', array($user_id));

        return parent::canEditUser($user_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getConnectionInfo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConnectionInfo', array());

        return parent::getConnectionInfo();
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray(array $data = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($data));

        return parent::exchangeArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', array());

        return parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function onPreUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPreUpdate', array());

        return parent::onPreUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function delete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'delete', array());

        return parent::delete();
    }

}
