<?php

$title = ($user->connection_id) ? 'Edit Connection' : 'Add Connection';
$title = $user->first_name . " " . $user->last_name . ": " . $title;
$this->headTitle($title);

$form = $this->form;

$params = array(
    'action'        => 'connectionEdit',
    'connection_id' => $this->connection_id,
);

if ($this->connection_string) {
    $params['connection_string'] = $this->connection_string;
}

$form->setAttribute('action', $this->url(
    'admin',
    $params
));

$this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger">')
        ->setMessageSeparatorString('</div><div class="alert alert-danger">')
        ->setMessageCloseString('</div>');

$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('user_id'));
echo $this->formHidden($form->get('connection_id'));
?>

<div class="container">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-11">
            <h2><?php echo $this->escapeHtml($title); ?></h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-9"><hr></div>
    </div>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-3">
            <div class="form-group">
                <?php
                    $element = $form->get('display_name');
                    echo $this->formRow($element, null, false);
                    echo $this->formElementErrors($element);
                ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <?php
                    $element = $form->get('driver');
                    echo $this->formRow($element, null, false);
                    echo $this->formElementErrors($element);
                ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <?php
                    $element = $form->get('is_server_connection');
                    echo $this->formRow($element, null, false);
                    echo $this->formElementErrors($element);
                ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-3">
            <div class="form-group">
                <?php
                    $element = $form->get('host');
                    echo $this->formRow($element, null, false);
                    echo $this->formElementErrors($element);
                ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <?php
                    $element = $form->get('user_name');
                    echo $this->formRow($element, null, false);
                    echo $this->formElementErrors($element);
                ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <?php
                    $element = $form->get('database_name');
                    echo $this->formRow($element, null, false);
                    echo $this->formElementErrors($element);
                ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-3">
            <div class="form-group">
                <?php
                    $element = $form->get('password');
                    echo $this->formRow($element, null, false);
                    echo $this->formElementErrors($element);
                ?>
            </div>
        </div>
        <div class="col-md-3">
            <div class="form-group">
                <?php
                    $element = $form->get('verify_password');
                    echo $this->formRow($element, null, false);
                    echo $this->formElementErrors($element);
                ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-9"><hr></div>
    </div>
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-3">
            <?php echo $this->formSubmit($form->get('save_submit')) ?>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>