<?php

$params = array();

if ($this->connection_string) {
    $params['connection_string'] = $this->connection_string;
}

?>

<?php if ($users): ?>
    <div class="page-header">
        <h3>
            <strong>User List</strong>
        </h3>
    </div>
    <div class="row">
        <div style="overflow-x: auto;">
            <table class="table table-condensed table-striped">
                <thead>
                <tr>
                    <th>User Name</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($users as $user): ?>
                <tr>
                    <td>
                        <?php
                            $params['action']  = 'edit';
                            $params['user_id'] = $user->user_id;
                        ?>
                        <a href="<?php echo $this->url('admin', $params) ?>">
                            <?php echo $user->user_name ?>
                        </a>
                    </td>
                    <td><?php echo $user->first_name ?></td>
                    <td><?php echo $user->last_name ?></td>
                    <td>
                        <?php
                            $params['action']  = 'connectionList';
                            $params['user_id'] = $user->user_id;
                        ?>
                        <a href="<?php echo $this->url('admin', $params) ?>">
                            Modify Connections
                        </a>
                    </td>
                </tr>
                <?php endforeach ?>
                </tbody>
            </table>
            <div class="well">
                <?php
                    $params['action'] = 'edit';
                    unset($params['user_id']);
                ?>
                <a href="<?php echo $this->url('admin', $params) ?>" class="btn btn-success">Add</a>
            </div>
        </div>
    </div>
<?php endif ?>