<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('dBoss') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- The styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/codemirror.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/nav-list.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <?php
            $params = ($this->connection_string) ? array('connection_string' => $this->connection_string) : null;

            $connection_name = null;

            if ($this->connection_string) {
                list($connection_id, $database_name) = explode("-", $this->connection_string);

                $connection_name = $database_name;

                if ($this->host_name) {
                    $connection_name = $this->host_name . ", " . $connection_name;
                }
            }
        ?>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home', $params) ?>">
                        <img src="<?php echo $this->basePath('img/db-logo.png') ?>" alt="dBoss"/>&nbsp;<?php echo $this->translate('dBoss') ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('schema', $params) ?>"><?php echo $this->translate('Schema') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('query', $params) ?>"><?php echo $this->translate('Query') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home', $params) ?>"><?php echo $this->translate('History') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('home', $params) ?>"><?php echo $this->translate('Saved') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('database', $params) ?>"><?php echo $this->translate('Databases') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $this->url('admin', $params) ?>"><?php echo $this->translate('Admin') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav pull-right">
                        <?php if ($connection_name): ?>
                            <li><a href="<?php echo $this->url('database', $params) ?>"><?php echo $connection_name ?></a></li>
                        <?php endif ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php
                echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
                echo $this->flashMessenger()->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
                echo $this->flashMessenger()->render('default', array('alert', 'alert-dismissable', 'alert-warning'));
                echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success'));
                
                echo $this->content;
            ?>
            <hr>
            <footer>
                <p>Database management that doesn't suck.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
