<?php if ($user): ?>
    <div class="page-header">
        <h3>
            <strong><?php echo $user->first_name . " " . $user->last_name ?>: Connections</strong>
        </h3>
    </div>
    <div class="row">
        <div style="overflow-x: auto;">
            <table class="table table-condensed table-striped">
                <thead>
                <tr>
                    <th>Display Name</th>
                    <th>Driver</th>
                    <th>Host</th>
                    <th>Database Name</th>
                    <th>User Name</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($user->connections as $connection): ?>
                <tr>
                    <td>
                        <?php
                            $params = array(
                                'action'        => 'connectionEdit',
                                'user_id'       => $connection->user_id,
                                'connection_id' => $connection->connection_id,
                            );
                        ?>
                        <a href="<?php echo $this->url('admin', $params) ?>">
                            <?php echo $connection->display_name ?>
                        </a>
                    </td>
                    <td>
                        <?php echo $connection->driver ?>
                    </td>
                    <td>
                        <?php echo $connection->host ?>
                    </td>
                    <td>
                        <?php echo $connection->database_name ?>
                    </td>
                    <td>
                        <?php echo $connection->user_name ?>
                    </td>
                </tr>
                <?php endforeach ?>
                </tbody>
            </table>
            <div class="well">
                <?php
                    $params = array(
                        'action'  => 'connectionEdit',
                        'user_id' => $user->user_id,
                    );
                ?>
                <a href="<?php echo $this->url('admin', $params) ?>" class="btn btn-success">Add</a>
            </div>
        </div>
    </div>
<?php endif ?>