<?php if ($users): ?>
    <div class="page-header">
        <h3>
            <strong>User List</strong>
        </h3>
    </div>
    <div class="row">
        <div style="overflow-x: auto;">
            <table class="table table-condensed table-striped">
                <thead>
                <tr>
                    <th>User Name</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($users as $user): ?>
                <tr>
                    <td>
                        <a href="<?php echo $this->url('admin', array('action' => 'edit', 'user_id' => $user->user_id)) ?>">
                            <?php echo $user->user_name ?>
                        </a>
                    </td>
                    <td><?php echo $user->first_name ?></td>
                    <td><?php echo $user->last_name ?></td>
                </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif ?>