<div class="row">
    <?php if ($this->resource_type == "table"): ?>

    <?php
        $params = array(
            'action'            => 'index',
            'schema_name'       => $this->schema_name,
            'resource_name'     => $this->resource_name,
            'connection_string' => $this->connection_string,
        );
    ?>
    <div class="col-md-2">
        <ul class="nav nav-list">
            <li class="nav-header">
                Actions
            </li>
            <li>
                <?php
                    $params['query_type']       = 'Select';
                    $params['with_field_names'] = 0;
                ?>
                <a href="<?php echo $this->url('query', $params) ?>">SELECT *</a>
            </li>
            <li>
                <?php
                    $params['query_type']       = 'Select';
                    $params['with_field_names'] = 1;
                ?>
                <a href="<?php echo $this->url('query', $params) ?>">SELECT FIELDS</a>
            </li>
            <li>
                <?php
                    $params['query_type'] = 'SelectJoin';
                    unset($params['with_field_names']);
                ?>
                <a href="<?php echo $this->url('query', $params) ?>">SELECT+JOINS</a>
            </li>
            <li>
                <?php
                    $params['query_type'] = 'Insert';
                ?>
                <a href="<?php echo $this->url('query', $params) ?>">INSERT</a>
            </li>
            <li>
                <?php
                    $params['query_type'] = 'Update';
                ?>
                <a href="<?php echo $this->url('query', $params) ?>">UPDATE</a>
            </li>
            <li>
                <?php
                    $params['query_type'] = 'Delete';
                ?>
                <a href="<?php echo $this->url('query', $params) ?>">DELETE</a>
            </li>
        </ul>
    </div>
    <?php endif ?>

    <div class="col-md-10">
        <h3>
            <a href="javascript::void();" onclick="history.back()">Definition: <?php echo $this->resource ?></a>
        </h3>
    </div>
    <div class="col-md-10">
        <pre><code class="sql"><?php echo $this->definition ?></code></pre>
    </div>
</div>