<div class="row-fluid">
    <div class="span8">

        <?php
            $params = array(
                'connection_string' => $this->connection_string,
                'action'            => 'index'
            );
        ?>
        <form action="<?php echo $this->url('schema', $params) ?>" id="schema_form" method="get">
             <div class="input-group">
                <span class="input-group-btn">
                    <button name="search_submit" id="search_button" class="btn btn-default" type="submit">Search</button>
                </span>
                <input type="text" name="search" id="search" class="form-control" value="<?php echo $form->get('search')->getValue() ?>">
            </div>
        </form>

        <?php if ($this->row_count): ?>
            <div id="table_menu" class="left left_menu">
                <h3><strong><?php echo $this->row_count ?></strong> results found</h3>
                
                <?php echo "<br/>" . $this->not_implemented; ?>

                <div class="auto_scroll">
                <?php if ($results): ?>
                    <table id="tables" class="full_width">
                        <tbody>
                        <?php foreach ($results as $encoded_id => $row): ?>
                        <!-- wow wtf -->
                        <?php $args = ($row['resource_arguments']) ? ($row['resource_arguments']) : "0"; ?>
                        <?php $table_name = (isset($row['table_name'])) ? ($row['table_name']) : "0"; ?>
                        <tr>
                            <td>
                                <a name="<?php echo $encoded_id ?>" href="<?php echo $this->url('schema',
                                            array(
                                                'action'             => 'definition',
                                                'connection_string'  => $this->connection_string,
                                                'schema_name'        => $row['schema_name'],
                                                'table_name'         => $table_name,
                                                'resource_name'      => $row['resource_name'],
                                                'resource_arguments' => $args,
                                                'resource_type'      => $row['resource_type'],
                                                'resource_value'     => $row['display']
                                            )
                                        ) ?>"><?php echo $row['display'] ?></a>
                                <em style="color: #999999"><?php echo $row['resource_type'] ?></em>
                            </td>
                        </tr>
                        <?php endforeach ?>
                        </tbody>
                    </table>
                <?php endif ?>
                </div>
            </div>
        <?php endif ?>

    </div>
</div>