<div class="row">
    <?php if ($this->resource_type == "table"): ?>
    <div class="col-md-2">
        <ul class="nav nav-list">
            <li class="nav-header">
                Actions
            </li>
            <li>
                <a href="<?php echo $this->url(
                    'query',
                    array(
                        'action'           => 'index',
                        'query_type'       => 'select',
                        'schema_name'      => $this->schema_name,
                        'resource_name'    => $this->resource_name,
                        'with_field_names' => 0
                )) ?>">SELECT *</a>
            </li>
            <li>
                <a href="<?php echo $this->url(
                    'query',
                    array(
                        'action'           => 'index',
                        'query_type'       => 'select',
                        'schema_name'      => $this->schema_name,
                        'resource_name'    => $this->resource_name,
                        'with_field_names' => 1
                )) ?>">SELECT FIELDS</a>
            </li>
            <li>
                <a href="<?php echo $this->url(
                    'query',
                    array(
                        'action'           => 'index',
                        'query_type'       => 'insert',
                        'schema_name'      => $this->schema_name,
                        'resource_name'    => $this->resource_name
                )) ?>">INSERT</a>
            </li>
            <li>
                <a href="<?php echo $this->url(
                    'query',
                    array(
                        'action'           => 'index',
                        'query_type'       => 'update',
                        'schema_name'      => $this->schema_name,
                        'resource_name'    => $this->resource_name
                )) ?>">UPDATE</a>
            </li>
            <li>
                <a href="<?php echo $this->url(
                    'query',
                    array(
                        'action'           => 'index',
                        'query_type'       => 'delete',
                        'schema_name'      => $this->schema_name,
                        'resource_name'    => $this->resource_name
                )) ?>">DELETE</a>
            </li>
        </ul>
    </div>
    <?php endif ?>

    <div class="col-md-10">
        <h3>
            <a href="javascript::void();" onclick="history.back()">Definition: <?php echo $this->resource ?></a>
        </h3>
    </div>
    <div class="col-md-10">
        <pre><code class="sql"><?php echo $this->definition ?></code></pre>
    </div>
</div>